syntax = "proto3";
import "google/protobuf/empty.proto";
package auth.v1;

option java_multiple_files = true;
option java_package = "auth.contract.v1";

service AuthRpcService {
  rpc GetAuthHealth(google.protobuf.Empty) returns (GetAuthHealthGrpcResponse);
  rpc Login(LoginAuthGrpcRequest) returns (LoginAuthGrpcResponse);
  rpc Signup(SignupAuthGrpcRequest) returns (google.protobuf.Empty);
  rpc Logout(LogoutAuthGrpcRequest) returns (google.protobuf.Empty);
  rpc Refresh(RefreshAuthGrpcRequest) returns (RefreshAuthGrpcResponse);
  rpc ChangePassword(ChangePasswordGrpcRequest) returns (google.protobuf.Empty);
  rpc BlockAuthUser(BlockAuthGrpcRequest) returns (google.protobuf.Empty);
  rpc UnlockAuthUser(UnlockAuthGrpcRequest) returns (google.protobuf.Empty);
  rpc VerifyAuthUserByCode(VerifyAuthUserByCodeGrpcRequest) returns (VerifyAuthUserByCodeGrpcResponse);
  rpc VerifyAuthUserByPrivilegeRole(VerifyAuthUserByPrivilegeRoleGrpcRequest) returns (google.protobuf.Empty);
  rpc ChangeAuthUserRole(ChangeAuthUserRoleGrpcRequest) returns (google.protobuf.Empty);
  rpc GetAuthUserById(GetAuthUserByIdGrpcRequest) returns (GetAuthUserByIdGrpcResponse);
  rpc ForgetPassword(ForgetPasswordGrpcRequest) returns (google.protobuf.Empty);
  rpc ResetPassword(ResetPasswordGrpcRequest) returns (ResetPasswordsGrpcResponse);
  rpc SocialLogin (SocialLoginGrpcRequest) returns (SocialLoginGrpcResponse);
}

message GetAuthHealthGrpcResponse {
  string message = 1;
}

message LoginAuthGrpcRequest {
  string email = 1;
  string password = 2;
}

message AuthTokenResponse {
  string accessToken = 1;
  string refreshToken = 2;
  int32 accessTokenMinutesTtl = 3;
  int32 refreshTokenDaysTtl = 4;
}

message LoginAuthGrpcResponse {
  AuthTokenResponse tokens = 1;
}

message SignupAuthGrpcRequest {
  string email = 1;
  string password = 2;
  string firstName = 3;
  string lastName = 4;
}

message LogoutAuthGrpcRequest {
  string refreshToken = 1;
}

message RefreshAuthGrpcRequest {
  string refreshToken = 1;
}

message RefreshAuthGrpcResponse {
  AuthTokenResponse tokens = 1;
}

message ChangePasswordGrpcRequest {
  string authUserId = 1;
  string oldPassword = 2;
  string  newPassword = 3;
  string role = 4;
}

message BlockAuthGrpcRequest {
  string authUserId = 1;
}

message UnlockAuthGrpcRequest {
  string authUserId = 1;
}

message VerifyAuthUserByCodeGrpcRequest {
  string authUserId = 1;
  string verificationCode = 2;
}

message VerifyAuthUserByCodeGrpcResponse {
  AuthTokenResponse tokens = 1;
}

message VerifyAuthUserByPrivilegeRoleGrpcRequest {
  string authUserId = 1;
  string role = 2;
}

message ChangeAuthUserRoleGrpcRequest {
  string authUserId = 1;
  string role = 2;
}

message GetAuthUserByIdGrpcRequest {
  string authUserId = 1;
}

message SocialAccountResponse {
  string provider = 1;
  string email = 2;
}

message GetAuthUserByIdGrpcResponse {
  string authUserId = 1;
  string status = 2;
  string email = 3;
  string role = 4;
  repeated SocialAccountResponse socialAccounts = 5;
}

message ForgetPasswordGrpcRequest {
  string email = 1;
}

message ResetPasswordGrpcRequest {
  string authUserId = 1;
  string  newPassword = 2;
}

message ResetPasswordsGrpcResponse {
  AuthTokenResponse tokens = 1;
}

message SocialLoginGrpcRequest {
  string  provider = 1;
  string providerUserId = 2;
  string email = 3;
  bool isEmailVerified = 4;
  string firstName = 5;
  string lastName = 6;
}

message SocialLoginGrpcResponse {
  AuthTokenResponse tokens = 1;
}