syntax = "proto3";
import "google/protobuf/empty.proto";

package transaction.v1;
import "account.proto";
option java_multiple_files = true;
option java_package = "transaction.contract.v1";

service TransactionRpcService {
  rpc GetTransactionHealth(google.protobuf.Empty) returns (GetTransactionHealthGrpcResponse);
  rpc CreateTransaction(CreateTransactionGrpcRequest) returns (google.protobuf.Empty);
  rpc GetTransactionsByAccounts(GetTransactionsByAccountsGrpcRequest) returns (GetTransactionsByAccountsGrpcResponse);
  rpc WatchTransactionStatus(WatchTransactionStatusRequest)
      returns (stream TransactionStatusResponse);
}

message GetTransactionHealthGrpcResponse {
  string message = 1;
}

message CreateTransactionGrpcRequest {
  string sourceAccountId = 1;
  string targetAccountId = 2;
  int64 minorUnits = 3;
  string currency = 4;
  string  idempotencyKey = 5;
  string  sourceAuthUserId = 6;
  string  targetAuthUserId = 7;
  string  sourceCardId = 8;
}

message GetTransactionsByAccountsGrpcRequest {
  repeated account.v1.AccountResponse accounts = 1;
}

message TransactionResponse {
  int64 minorUnits = 1;
  string currency = 2;
  string status = 3;
  string  createdAt = 4;
  string completedAt = 5;
  account.v1.AccountResponse sourceAccount = 6;
  account.v1.AccountResponse targetAccount = 7;
  string transactionId = 8;
}

message GetTransactionsByAccountsGrpcResponse {
  repeated TransactionResponse transactions = 1;
}

message WatchTransactionStatusRequest {
  string transactionId = 1;
  string authUserId = 2;
  string subscriptionKey = 3;
}

message TransactionStatusResponse {
  int64 minorUnits = 1;
  string currency = 2;
  string status = 3;
  account.v1.AccountResponseWithoutSensitiveInfo sourceAccount = 4;
  account.v1.AccountResponseWithoutSensitiveInfo targetAccount = 5;
}
