syntax = "proto3";
import "google/protobuf/empty.proto";

package transaction.v1;

option java_multiple_files = true;
option java_package = "transaction.contract.v1";

service TransactionRpcService {
  rpc GetTransactionHealth(google.protobuf.Empty) returns (GetTransactionHealthGrpcResponse);
  rpc CreateTransaction(CreateTransactionGrpcRequest) returns (google.protobuf.Empty);
}

message GetTransactionHealthGrpcResponse {
  string message = 1;
}

message CreateTransactionGrpcRequest {
  string sourceAccountId = 1;
  string targetAccountId = 2;
  int64 amount = 3;
  string currency = 4;
  string  idempotencyKey = 5;
  string  authUserId = 6;
}
